/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.PanelCRUD;

import Clases.Alumno;
import Clases.ClienteWS;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.json.JSONException;

/**
 *
 * @author ReR-7
 */
public class ActualizarJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ActualizarJPanel
     */
    public ActualizarJPanel() {
        initComponents(); 
        initializeJComboBox(); 
        // Agregar un ComponentListener al JPanel
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent e) {
                ObtenerRegistros();
            }
        });
    }

    private void initializeJComboBox() {
        // Configuración del JComboBox
        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
        jcbMatriculas.setModel(comboBoxModel);

        // Configurar ActionListener para manejar los eventos de selección en el JComboBox
        jcbMatriculas.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                try {
                    String matriculaSeleccionada = (String) jcbMatriculas.getSelectedItem();
                    ClienteWS peticionHTTP = new ClienteWS();

                    // Supongo que el método MetodoGetm devuelve una lista de objetos Alumno
                    List<Alumno> alumnosConsultados = peticionHTTP.MetodoGetm(matriculaSeleccionada);

                    // Asegúrate de que la lista no esté vacía antes de actualizar los campos de texto
                    if (!alumnosConsultados.isEmpty()) {
                        Alumno alumnoSeleccionado = alumnosConsultados.get(0);

                        // Actualiza los campos de texto con los datos del alumno seleccionado
                        txtNombre.setText(alumnoSeleccionado.getNombre());
                        txtPaterno.setText(alumnoSeleccionado.getaPaterno());
                        txtMaterno.setText(alumnoSeleccionado.getaMaterno());
                        txtEdad.setText(alumnoSeleccionado.getEdad());
                        txtGrupo.setText(alumnoSeleccionado.getGrupo());
                        txtTelefono.setText(alumnoSeleccionado.getTelefono());
                        txtCorreo.setText(alumnoSeleccionado.getCorreo());
                        txtCuatri.setText(alumnoSeleccionado.getCuatrimestre());
                        txtPromedio.setText(alumnoSeleccionado.getPromedio());
                    }
                } catch (JSONException ex) {
                    Logger.getLogger(ActualizarJPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    private void ObtenerRegistros() {
        ClienteWS peticionHTTP = new ClienteWS();
        try {
            // Supongo que el método MetodoConsulta devuelve una lista de objetos Alumno
            List<Alumno> alumnosConsultados = peticionHTTP.MetodoConsulta();

            // Obtener el modelo del JComboBox
            DefaultComboBoxModel<String> comboBoxModel = (DefaultComboBoxModel<String>) jcbMatriculas.getModel();

            // Limpiar el contenido actual del JComboBox
            comboBoxModel.removeAllElements();

            // Agregar las matrículas consultadas al JComboBox
            for (Alumno alumno : alumnosConsultados) {
                comboBoxModel.addElement(alumno.getMatricula());
            }
        } catch (JSONException ex) {
            Logger.getLogger(ConsulatJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblActualizar = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        txtGrupo = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblGrupo = new javax.swing.JLabel();
        lblPaterno = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblMaterno = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtCuatri = new javax.swing.JTextField();
        lblCuatri = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPromedio = new javax.swing.JTextField();
        txtMaterno = new javax.swing.JTextField();
        lblPromedio = new javax.swing.JLabel();
        txtPaterno = new javax.swing.JTextField();
        lblEdad = new javax.swing.JLabel();
        jcbMatriculas = new javax.swing.JComboBox<>();
        lblSelect = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblActualizar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblActualizar.setForeground(new java.awt.Color(0, 0, 0));
        lblActualizar.setText("Actualizar Registro");

        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadKeyTyped(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Nombre:");

        lblGrupo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblGrupo.setForeground(new java.awt.Color(0, 0, 0));
        lblGrupo.setText("Grupo:");

        lblPaterno.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblPaterno.setForeground(new java.awt.Color(0, 0, 0));
        lblPaterno.setText("Apellido P.");

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        lblMaterno.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblMaterno.setForeground(new java.awt.Color(0, 0, 0));
        lblMaterno.setText("Apellido M.");

        lblTelefono.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(0, 0, 0));
        lblTelefono.setText("Telefono:");

        lblCorreo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(0, 0, 0));
        lblCorreo.setText("Correo:");

        lblCuatri.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblCuatri.setForeground(new java.awt.Color(0, 0, 0));
        lblCuatri.setText("Cuatrimestre:");

        txtNombre.setToolTipText("");
        txtNombre.setName(""); // NOI18N

        txtPromedio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPromedioKeyTyped(evt);
            }
        });

        lblPromedio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblPromedio.setForeground(new java.awt.Color(0, 0, 0));
        lblPromedio.setText("Promedio:");

        lblEdad.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblEdad.setForeground(new java.awt.Color(0, 0, 0));
        lblEdad.setText("Edad:");

        jcbMatriculas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblSelect.setForeground(new java.awt.Color(0, 0, 0));
        lblSelect.setText("Seleccione la matricula");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPaterno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lblMaterno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(btnActualizar)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblEdad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbMatriculas, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblSelect))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblGrupo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(lblTelefono)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblActualizar)
                        .addGap(190, 190, 190))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCuatri)
                                .addGap(18, 18, 18)
                                .addComponent(txtCuatri, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(214, 214, 214)
                                .addComponent(lblCorreo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPromedio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblActualizar)
                .addGap(32, 32, 32)
                .addComponent(lblSelect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbMatriculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaterno)
                    .addComponent(txtPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPaterno)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrupo)
                    .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEdad))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCuatri)
                    .addComponent(txtCuatri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPromedio)
                    .addComponent(txtPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(btnActualizar)
                .addGap(54, 54, 54))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros) {
            evt.consume();
        }

        if (txtEdad.getText().trim().length() == 3) {
            evt.consume();
        }
    }//GEN-LAST:event_txtEdadKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros) {
            evt.consume();
        }

        if (txtTelefono.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtPromedioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPromedioKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = (key >= 48 && key <= 57) || key == 46; // 46 representa el código ASCII del punto decimal

        if (!numeros) {
            evt.consume();
        }
        if (txtPromedio.getText().trim().length() == 5) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPromedioKeyTyped


    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String matriculaSeleccionada = (String) jcbMatriculas.getSelectedItem();
        ClienteWS peticionHTTP = new ClienteWS();
        Alumno AgregarAlumno = new Alumno();
        AgregarAlumno.setNombre(txtNombre.getText());
        AgregarAlumno.setaPaterno(txtPaterno.getText());
        AgregarAlumno.setaMaterno(txtMaterno.getText());
        AgregarAlumno.setMatricula(matriculaSeleccionada);
        AgregarAlumno.setEdad(txtEdad.getText());
        AgregarAlumno.setGrupo(txtGrupo.getText());
        AgregarAlumno.setTelefono(txtTelefono.getText());
        AgregarAlumno.setCorreo(txtCorreo.getText());
        AgregarAlumno.setCuatrimestre(txtCuatri.getText());
        AgregarAlumno.setPromedio(txtPromedio.getText());

        boolean exito = peticionHTTP.MetodoPut(AgregarAlumno);

        if (exito) {
            // Si el método fue exitoso (true), muestra un mensaje de éxito
            JOptionPane.showMessageDialog(this, "El alumno con matrícula " + matriculaSeleccionada + " ha sido actualizado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Si el método no fue exitoso (false), muestra un mensaje de error
            JOptionPane.showMessageDialog(this, "No se pudo actualizar el alumno con matrícula " + matriculaSeleccionada + ".", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JComboBox<String> jcbMatriculas;
    private javax.swing.JLabel lblActualizar;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCuatri;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblMaterno;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPaterno;
    private javax.swing.JLabel lblPromedio;
    private javax.swing.JLabel lblSelect;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCuatri;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtGrupo;
    private javax.swing.JTextField txtMaterno;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPaterno;
    private javax.swing.JTextField txtPromedio;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
