/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.PanelCRUD;

import javax.swing.table.DefaultTableModel;
import Clases.ClienteWS;
import Clases.Alumno;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.JSONException;

/**
 *
 * @author ReR-7
 */
public class ConsulatJPanel extends javax.swing.JPanel {

    DefaultTableModel modelo;

    /**
     * Creates new form ConsulatJPanel
     */
    public ConsulatJPanel() {
        initComponents();
        modelo = new DefaultTableModel();
        modelo.addColumn("Matricula");
        modelo.addColumn("Nombre");
        modelo.addColumn("A. Paterno");
        modelo.addColumn("A. Materno");
        modelo.addColumn("Edad");
        modelo.addColumn("Grupo");
        modelo.addColumn("Telefono");
        modelo.addColumn("Correo");
        modelo.addColumn("Cuatrimestre");
        modelo.addColumn("Promedio");
        this.TableAlumnos.setModel(modelo);

        // Agregar un ComponentListener al JPanel
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent e) {
                DefaultTableModel modelo = (DefaultTableModel) TableAlumnos.getModel();
                modelo.setRowCount(0);
                ObtenerRegistros();
            }
        });
    }

    private void ObtenerRegistros() {
        ClienteWS peticionHTTP = new ClienteWS();
        try {
            // Supongo que el método MetodoGetm devuelve una lista de objetos Alumno
            List<Alumno> alumnosConsultados = peticionHTTP.MetodoConsulta();

            // A continuación, puedes hacer lo que necesites con la lista de alumnos consultados
            // Por ejemplo, si quieres agregarlos a la tabla, puedes hacerlo mediante el modelo de datos
            DefaultTableModel modeloTabla = (DefaultTableModel) TableAlumnos.getModel();
            for (Alumno alumno : alumnosConsultados) {
                modeloTabla.addRow(new Object[]{
                    alumno.getMatricula(),
                    alumno.getNombre(),
                    alumno.getaPaterno(),
                    alumno.getaMaterno(),
                    alumno.getEdad(),
                    alumno.getGrupo(),
                    alumno.getTelefono(),
                    alumno.getCorreo(),
                    alumno.getCuatrimestre(),
                    alumno.getPromedio()
                });
            }
        } catch (JSONException ex) {
            Logger.getLogger(ConsulatJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConsuta = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableAlumnos = new javax.swing.JTable();
        txtMatricula = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        lblBuscaMatricula = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(500, 550));

        lblConsuta.setBackground(new java.awt.Color(255, 255, 255));
        lblConsuta.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblConsuta.setText("Consulta registros");

        TableAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TableAlumnos);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        lblBuscaMatricula.setText("Ingrese la matricula a buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnConsultar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(lblConsuta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(lblBuscaMatricula)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblConsuta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBuscaMatricula)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) TableAlumnos.getModel();
        modelo.setRowCount(0);
        ClienteWS peticionHTTP = new ClienteWS();
        try {
            // Supongo que el método MetodoGetm devuelve una lista de objetos Alumno
            List<Alumno> alumnosConsultados = peticionHTTP.MetodoGetm(txtMatricula.getText());

            // A continuación, puedes hacer lo que necesites con la lista de alumnos consultados
            // Por ejemplo, si quieres agregarlos a la tabla, puedes hacerlo mediante el modelo de datos
            DefaultTableModel modeloTabla = (DefaultTableModel) TableAlumnos.getModel();
            for (Alumno alumno : alumnosConsultados) {
                modeloTabla.addRow(new Object[]{
                    alumno.getMatricula(),
                    alumno.getNombre(),
                    alumno.getaPaterno(),
                    alumno.getaMaterno(),
                    alumno.getEdad(),
                    alumno.getGrupo(),
                    alumno.getTelefono(),
                    alumno.getCorreo(),
                    alumno.getCuatrimestre(),
                    alumno.getPromedio()
                });
            }
        } catch (JSONException ex) {
            Logger.getLogger(ConsulatJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableAlumnos;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBuscaMatricula;
    private javax.swing.JLabel lblConsuta;
    private javax.swing.JTextField txtMatricula;
    // End of variables declaration//GEN-END:variables
}
